# General properties
server.port=4000
server.address=0.0.0.0
spring.application.name=movie-ez-api
# Cache properties
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=300s,maximumSize=1000
# Database properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.connection.CharSet=utf8mb4
spring.jpa.properties.hibernate.connection.characterEncoding=utf8mb4
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.sql.init.mode=always
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.threads.virtual.enabled=true
# Security properties
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT-ISSUER-URI:http://localhost:8080/realms/movie-ez}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT-JWKS-URI:${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs}
# Message source (include exception messages)
spring.messages.basename=ExceptionMessages,ValidationMessages,messages
# Custom properties
app.tmdb.base-url=${TMDB_BASE_URL:https://api.themoviedb.org/3}
app.tmdb.api-key=${TMDB_API_KEY}
app.movieez.security.header=${SECURITY_HEADER_VALUE:#{null}}
# Custom keycloak properties
app.keycloak.admin.server-url=${KEYCLOAK_ADMIN_SERVER_URL:http://localhost:8080}
app.keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:movie-ez}
app.keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:movie-ez-api}
app.keycloak.admin.secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
# Debugging properties
spring.docker.compose.enabled=false
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}